### ISSUE TITLE
concurrent github jobs clash

### ISSUE THREAD

**Issue by bbortt** [bbortt/event-planner#735]
both the [`main`](https://github.com/bbortt/event-planner/blob/main/.github/workflows/main.yml) and the [`preview`](https://github.com/bbortt/event-planner/blob/main/.github/workflows/preview.yml) build use the same concurrency rules:
```yaml
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
```

therefore, they [cancel each other](https://github.com/bbortt/event-planner/actions/runs/4431170406):
> Canceling since a higher priority waiting request for 'refs/heads/feature/application-build' exists

they should include the `${{ github.job }}` key as well. e.g. `${{ github.job }}-${{ github.ref }}`.
